=== baloghbence0915/xquery_hw/schema/ex8.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="countries" type="countriesType"/>

    <xs:complexType name="countriesType">
        <xs:sequence>
            <xs:element name="country" type="countryType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="countryType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="num" type="xs:positiveInteger"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:schema>

=== baloghbence0915/xquery_hw/result8.xml
<?xml version="1.0" encoding="UTF-8"?>
<countries xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="schema/ex8.xsd">
   <country num="286">USA</country>
   <country num="89">United Kingdom</country>
   <country num="78">Germany</country>
   <country num="56">France</country>
   <country num="29">Sweden</country>
   <country num="27">Japan</country>
   <country num="24">Switzerland</country>
   <country num="21">Canada</country>
   <country num="18">the Netherlands</country>
   <country num="17">Italy</country>
   <country num="17">Russia</country>
   <country num="16">Austria</country>
   <country num="16">Russian Empire</country>
   <country num="13">Prussia</country>
   <country num="13">Austria-Hungary</country>
   <country num="12">Norway</country>
   <country num="11">Scotland</country>
   <country num="11">China</country>
   <country num="11">Denmark</country>
   <country num="11">Australia</country>
   <country num="10">India</country>
   <country num="10">Belgium</country>
   <country num="9">South Africa</country>
   <country num="9">Poland</country>
   <country num="7">Hungary</country>
   <country num="7">Spain</country>
   <country num="6">Egypt</country>
   <country num="5">Northern Ireland</country>
   <country num="5">West Germany</country>
   <country num="5">British Mandate of Palestine</country>
   <country num="5">Ireland</country>
   <country num="5">USSR</country>
   <country num="4">Austrian Empire</country>
   <country num="4">Argentina</country>
   <country num="4">Romania</country>
   <country num="3">New Zealand</country>
   <country num="3">Mexico</country>
   <country num="2">East Timor</country>
   <country num="2">Portugal</country>
   <country num="2">Luxembourg</country>
   <country num="2">Guatemala</country>
   <country num="2">Chile</country>
   <country num="2">Colombia</country>
   <country num="2">Schleswig</country>
   <country num="2">British India</country>
   <country num="2">Turkey</country>
   <country num="2">Finland</country>
   <country num="2">French Algeria</country>
   <country num="2">Ottoman Empire</country>
   <country num="2">Korea</country>
   <country num="2">Liberia</country>
   <country num="1">Cyprus</country>
   <country num="1">WÃ¼rttemberg</country>
   <country num="1">Tibet</country>
   <country num="1">Bavaria</country>
   <country num="1">Iceland</country>
   <country num="1">Guadeloupe Island</country>
   <country num="1">Java, Dutch East Indies</country>
   <country num="1">Belgian Congo</country>
   <country num="1">Morocco</country>
   <country num="1">Iran</country>
   <country num="1">Brazil</country>
   <country num="1">Iraq</country>
   <country num="1">Czechoslovakia</country>
   <country num="1">Gold Coast</country>
   <country num="1">Faroe Islands (Denmark)</country>
   <country num="1">Ukraine</country>
   <country num="1">British Protectorate of Palestine</country>
   <country num="1">Tuscany</country>
   <country num="1">Mecklenburg</country>
   <country num="1">Taiwan</country>
   <country num="1">Trinidad and Tobago</country>
   <country num="1">Peru</country>
   <country num="1">Yemen</country>
   <country num="1">Ethiopia</country>
   <country num="1">Crete</country>
   <country num="1">East Friesland</country>
   <country num="1">Madagascar</country>
   <country num="1">British West Indies</country>
   <country num="1">Costa Rica</country>
   <country num="1">Bosnia</country>
   <country num="1">German-occupied Poland</country>
   <country num="1">Pakistan</country>
   <country num="1">Vietnam</country>
   <country num="1">Lithuania</country>
   <country num="1">Southern Rhodesia</country>
   <country num="1">Bulgaria</country>
   <country num="1">Nigeria</country>
   <country num="1">Persia</country>
   <country num="1">Hesse-Kassel</country>
   <country num="1">Burma</country>
   <country num="1">Kenya</country>
   <country num="1">Venezuela</country>
   <country num="1">Saint Lucia</country>
   <country num="1">Bangladesh</country>
   <country num="1">Free City of Danzig</country>
</countries>
