=== baloghbence0915/xquery_hw/schema/ex9.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="laurates" type="lauratesType"/>

    <xs:complexType name="lauratesType">
        <xs:sequence>
            <xs:element name="laurate" type="laurateType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="laurateType">
        <xs:sequence>
            <xs:element name="name" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="age" type="xs:positiveInteger"/>
    </xs:complexType>
</xs:schema>

=== baloghbence0915/xquery_hw/result9.xml
<?xml version="1.0" encoding="UTF-8"?>
<laurates xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="schema/ex9.xsd">
   <laurate age="17">
      <name>Malala Yousafzai</name>
   </laurate>
   <laurate age="25">
      <name>William Lawrence Bragg</name>
      <name>Nadia Murad Basee Taha</name>
   </laurate>
   <laurate age="31">
      <name>Carl David Anderson</name>
      <name>Paul Adrien Maurice Dirac</name>
      <name>Tsung-Dao (T.D.) Lee</name>
      <name>Werner Karl Heisenberg</name>
   </laurate>
   <laurate age="32">
      <name>Frederick Grant Banting</name>
      <name>Mairead Corrigan</name>
      <name>Rudolf Ludwig Mössbauer</name>
      <name>Tawakkol Karman</name>
   </laurate>
   <laurate age="33">
      <name>Elizabeth Williams</name>
      <name>Brian David Josephson</name>
      <name>Joshua Lederberg</name>
      <name>Rigoberta Menchú Tum</name>
   </laurate>
   <laurate age="34">
      <name>Donald Arthur Glaser</name>
      <name>James Dewey Watson</name>
   </laurate>
   <laurate age="35">
      <name>Arthur Holly Compton</name>
      <name>Chen Ning Yang</name>
      <name>Frédéric Joliot</name>
      <name>Guglielmo Marconi</name>
      <name>Martin Luther King Jr.</name>
      <name>Max von Laue</name>
   </laurate>
   <laurate age="36">
      <name>Adolf Friedrich Johann Butenandt</name>
      <name>Archibald Vivian Hill</name>
      <name>Konstantin Novoselov</name>
      <name>Marie Curie, née Sklodowska</name>
   </laurate>
   <laurate age="37">
      <name>David Baltimore</name>
      <name>Enrico Fermi</name>
      <name>Ernest Rutherford</name>
      <name>J. Georg Bednorz</name>
      <name>Prince Louis-Victor Pierre Raymond de Broglie</name>
      <name>Niels Henrik David Bohr</name>
      <name>Pieter Zeeman</name>
   </laurate>
   <laurate age="38">
      <name>Ernest Orlando Lawrence</name>
      <name>Frederick Chapman Robbins</name>
      <name>Georges J.F. Köhler</name>
      <name>Gustav Ludwig Hertz</name>
      <name>Irène Joliot-Curie</name>
      <name>Karl Manne Georg Siegbahn</name>
      <name>Otto Fritz Meyerhof</name>
      <name>Richard Kuhn</name>
      <name>Richard Laurence Millington Synge</name>
      <name>Robert Bárány</name>
   </laurate>
</laurates>
